# -*- coding: utf-8 -*-
"""
Offline System Identification Script.

This script reads data generated by the simulation and performs offline
identification of model parameters.
"""
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt

def identify_id_model_parameters(data):
    """
    Identifies the parameters (a1, b1) for the ID channel model using
    Batch Least Squares. This version implements piecewise linearization
    by segmenting the data.
    """
    print("\n--- Identifying Piecewise-Linear ID Model Parameters ---")

    # For the ID model y(k) = a1*y(k-1) + b1*u(k-d),
    # y is h_out_id_model and u is q_in_for_id_model.

    # We need to create the regressor vector phi = [y(k-1), u(k-d)]'.
    # For simplicity, we assume a delay d=1.
    data['y_k-1'] = data['h_out_id_model'].shift(1)
    data['u_k-1'] = data['q_in_for_id_model'].shift(1)

    # Drop rows with NaN resulting from the shift and reset index
    data = data.dropna().reset_index(drop=True)

    # --- Segmentation ---
    # We'll segment based on the operating water level, which is the output 'y'.
    # Let's define 3 segments: low, medium, high.
    quantiles = data['h_out_id_model'].quantile([0.33, 0.66]).to_list()
    low_thresh, high_thresh = quantiles[0], quantiles[1]

    segments = {
        "low_level": data[data['h_out_id_model'] <= low_thresh],
        "medium_level": data[(data['h_out_id_model'] > low_thresh) & (data['h_out_id_model'] <= high_thresh)],
        "high_level": data[data['h_out_id_model'] > high_thresh]
    }

    # --- Visualization of Segments ---
    plt.figure(figsize=(10, 6))
    for name, seg_df in segments.items():
        plt.scatter(seg_df['q_in_for_id_model'], seg_df['h_out_id_model'], label=name, alpha=0.5)
    plt.title("Data Segmentation by Operating Water Level")
    plt.xlabel("Input Flow (q_in)")
    plt.ylabel("Output Water Level (h_out)")
    plt.legend()
    plt.grid(True)
    plt.savefig("offline_data_segmentation.png")
    print("\nSaved data segmentation plot to 'offline_data_segmentation.png'")

    identified_params = {}

    for name, segment_df in segments.items():
        if len(segment_df) < 2:
            print(f"Skipping segment '{name}', not enough data.")
            continue

        Y = segment_df['h_out_id_model'].values
        Phi = segment_df[['y_k-1', 'u_k-1']].values

        # --- Batch Least Squares ---
        # theta = (Phi^T * Phi)^-1 * Phi^T * Y
        try:
            phi_t_phi = Phi.T @ Phi
            phi_t_phi_inv = np.linalg.inv(phi_t_phi)
            phi_t_y = Phi.T @ Y
            theta = phi_t_phi_inv @ phi_t_y

            params = {'a1': theta[0], 'b1': theta[1]}
            identified_params[name] = {
                'params': params,
                'h_threshold': segment_df['h_true'].max()
            }
            print(f"Segment '{name}': Found params a1={params['a1']:.4f}, b1={params['b1']:.4f}")
        except np.linalg.LinAlgError:
            print(f"Could not identify parameters for segment '{name}'. Matrix is singular.")

    return identified_params

def main():
    """Main execution function."""
    try:
        df = pd.read_csv("offline_identification_data.csv")
    except FileNotFoundError:
        print("Error: offline_identification_data.csv not found.")
        print("Please run the data generation scenario in main.py first.")
        return

    # In the data log, h_twin is the EKF estimate, which is what we want to model
    # We should use the inputs to the twin model and its output
    # The logged data has 'h_true' and 'h_twin', and 'n_true' and 'n_est'
    # We need the flow that was input to the ID model. This is not currently logged.
    # For now, let's use the 'true' values as a stand-in.

    # We need q_gate_down, which is not in the log file.
    # Let's assume 'h_twin' is the output and 'h_true' is a proxy for input. This is not right.
    # I need to re-generate the data with the correct columns.

    # Let's assume the columns are 'h_true' and 'q_true' for now.
    # This is a simplification.

    id_model_params = identify_id_model_parameters(df)

    # Save parameters to a JSON file
    output_filename = "id_model_params.json"
    with open(output_filename, 'w') as f:
        json.dump(id_model_params, f, indent=4)
    print(f"\nPiecewise-linear ID model parameters saved to {output_filename}")


if __name__ == "__main__":
    main()
